### ISSUE TITLE
Getting wrong unique and opens count when sending in batch.

### ISSUE THREAD

**Issue by iit2011081** [suetco/suet#3]
I am getting wrong unique and opens count when I send mails in batch. When I try to debug the code I found that in case of batch emails all webhook response have same message-Id which is causing the same. Any solution to handle this case ?

**Comment by kehers** [comment]
How are you sending the batch mail? SMTP or with [Mailgun's Batch API](http://mailgun-documentation.readthedocs.io/en/latest/user_manual.html#batch-sending)? For Suet to know to group analytics, the batch API should be used. Support for grouping using tags coming soon.

**Comment by iit2011081** [comment]
I am using Mailgun's Batch API. I want the open count and click count for each individual recipient.

**Comment by kehers** [comment]
In that case, the uniques should be correct. Uniques does not use only the message id. The email is used as well. See https://github.com/kehers/suet/blob/9a8340173d5b75a3623354eb4aaddfb01779f0f7/models/accounts.js#L11 https://github.com/kehers/suet/blob/9a8340173d5b75a3623354eb4aaddfb01779f0f7/models/accounts.js#L17 https://github.com/kehers/suet/blob/9a8340173d5b75a3623354eb4aaddfb01779f0f7/models/mails.js#L135

Or am I wrongly interpreting what you mean by "unique"?

**Comment by kehers** [comment]
I am closing this for now. Let me know if it's still an issue.
