### ISSUE TITLE
Seems not support the new mailgun api

### ISSUE THREAD

**Issue by huhongbo** [suetco/suet#5]
Cannot work with the new mailgun api because the webhook return is not multipart/form-data  and event data is different

**Comment by kehers** [comment]
This has changed on the managed version @ suet.co. This repo will be updated with support for the new version soon.

**Comment by MACscr** [comment]
Its been a couple months. Update?

**Comment by kehers** [comment]
A new version is now available that supports the new Mailgun API and also adds support for Amazon SES. Please see the [installation doc](https://github.com/suetco/suet/blob/master/docs/installation.md) for setup details.
